# This workflow will do a clean install of node dependencies and run Prettier

name: Prettier

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Node 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm ci
            - run: npm run prettier:check
